name: .NET Playwright CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0" # Ajusta según la versión de .NET que uses

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev \
            libxcomposite1 \
            libxrandr2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libx11-xcb1 \
            libnss3 \
            libnspr4 \
            libu2f-udev \
            libvulkan1 \
            libasound2-plugins

      - name: Install Playwright
        run: |
          npm install -g playwright

      - name: Run Playwright tests
        run: |
          dotnet test --configuration Release
